language: node_js
node_js:
  - 8
  - 6
  - 4
services:
  - mongodb
before_script: "npm run add-mongoose"
script: "npm run-script test-travis"
after_script: "npm install coveralls@3.0.0 && cat ./coverage/lcov.info | coveralls"
